theme {
    # Сюда Matugen будет складывать цвета
    color_scheme = ~/.local/share/color-schemes/matugen.colors

    # Указываем установленный пак Arcticons
    icon_theme = Arcticons

    # Fusion дает максимально плоский Material-вид без лишних теней и градиентов
    style = Fusion

    # Шрифты Google
    font = Roboto
    font_size = 10
    
    font_fixed = Roboto Mono
    font_fixed_size = 10
}

misc {
    single_click_activate = true
    menus_have_icons = false
    shortcuts_for_context_menus = false
}
