hl.animation({ leaf = "workspaces", enabled = true, speed = 10, bezier = "androidFluid", style = "fade" })
hl.curve("androidOpen",  { type = "bezier", points = { {0.34, 1.3}, {0.64, 1} } })
hl.curve("androidClose", { type = "bezier", points = { {0.25, 1},   {0.5, 1} } })
hl.curve("androidFluid", { type = "bezier", points = { {0.2, 0.8},   {0.2, 1} } })
hl.animation({ leaf = "windows", enabled = true, speed = 3, bezier = "androidOpen", style = "popin 80%" })
hl.animation({ leaf = "windowsIn",   enabled = true, speed = 4,  bezier = "androidOpen" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 3,  bezier = "androidClose" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4,  bezier = "androidFluid" })
hl.animation({ leaf = "layers",    enabled = true, speed = 3, bezier = "androidOpen", style = "slide top" })
hl.animation({ leaf = "layersIn",  enabled = true, speed = 4, bezier = "androidOpen" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 3, bezier = "androidClose" })
hl.animation({ leaf = "hyprfocusIn",  enabled = true, speed = 5, bezier = "androidOpen" })
hl.animation({ leaf = "hyprfocusOut", enabled = true, speed = 4, bezier = "androidClose" })
hl.animation({ leaf = "border", enabled = true, speed = 4, bezier = "androidFluid" })
