#!/bin/bash

MODE="$1"

case "$MODE" in
    dark|light)
        ;;
    *)
        exit 1
        ;;
esac

# ==========================================
# MATUGEN
# ==========================================

matugen image \
    --prefer saturation \
    ~/.config/hypr/wallpaper.png \
    -m "$MODE"


# ==========================================
# ЗДЕСЬ ПОТОМ МОЖНО ДОБАВЛЯТЬ ДРУГИЕ СИСТЕМЫ
# ==========================================

# Например:
# gsettings set org.gnome.desktop.interface color-scheme "prefer-$MODE"

# Например:
# hyprctl reload

# Например:
# pkill -SIGUSR2 waybar

# Например:
# kitty @ set-colors ...
